/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/Accordion.vue')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CitySelect: typeof import('./src/components/CitySelect.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    ExpandableText: typeof import('./src/components/ExpandableText.vue')['default']
    Extensions: typeof import('./src/components/Extensions.vue')['default']
    FastStart: typeof import('./src/components/FastStart.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MarqueeText: typeof import('./src/components/MarqueeText.vue')['default']
    NoticeBar: typeof import('./src/components/NoticeBar.vue')['default']
    Picker: typeof import('./src/components/Picker.vue')['default']
    Popover: typeof import('./src/components/Popover.vue')['default']
    PopupMessage: typeof import('./src/components/PopupMessage.vue')['default']
    Radio: typeof import('./src/components/Radio.vue')['default']
    Rating: typeof import('./src/components/Rating.vue')['default']
    Refresh: typeof import('./src/components/Refresh.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusView: typeof import('./src/components/StatusView.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    TestComponents: typeof import('./src/components/TestComponents.vue')['default']
    Utils: typeof import('./src/components/Utils.vue')['default']
  }
}
